export const FETCH_ATTRIBUTES_START = 'FETCH__ATTRIBUTES_START';
export const FETCH_ATTRIBUTES_SUCCESS = 'FETCH__ATTRIBUTES_SUCCESS';
export const FETCH_ATTRIBUTES_FAILURE = 'FETCH__ATTRIBUTES_FAILURE';
export const FETCH_ATTRIBUTES_CLEAR = 'FETCH__ATTRIBUTES_CLEAR';